<?php
  function osteo_contact_form_contact_site_form_alter(&$form, &$form_state, $form_id) {
    $choix_cab      = array(
      'Roman' => 'Roman',
      'Valence' => 'Valence',
      'Allex' => 'Allex',
    );
    $form['prenom'] = array(
      '#type'          => 'textfield',
      '#title'         => 'Prénom',
      '#default_value' => '',
      '#size'          => 60,
      '#maxlength'     => 128,
      '#required'      => TRUE,
      '#weight'        => 1
    );

    $form['mail']['#title']                 = 'Adresse Email';
    $form['mail']['#maxlength']             = 128;
    $form['mail']['#weight']                = 2;
    $form['mail']['#attributes']['onkeyup'] = 'controle_mail()';
    $form['#attached']['js']                = array(drupal_get_path('module', 'osteo_contact') . '/js/osteo_contact.js');
    $form['#validate'][]                    = "validate_email";

    $form['cabinet']['#title']   = 'Choix du cabinet';
    $form['cabinet']['#type']    = 'select';
    $form['cabinet']['#options'] = $choix_cab;


    $form['subject']['#access'] = FALSE;

    $form['cid']['#title']     = 'Votre demande';
    $form['cid']['#maxlength'] = 128;
    $form['cid']['#weight']    = 4;

    $form['message']['#title']     = 'Message';
    $form['message']['#maxlength'] = 128;
    $form['message']['#weight']    = 5;

    unset($form['copy']);

    $form['actions']['submit']['#value'] = "Envoyer";
    return $form;
  }

  function osteo_contact_menu_alter(&$items) {
    $items['admin/structure/contact']['page callback'] = 'BO_contact_add_description';
  }

  function BO_contact_add_description() {
    $form                  = drupal_get_form('description_contact_form');
    $output                = contact_category_list();
    $output['description'] = $form;
    return $output;
  }

  function description_contact_form($form, &$form_state) {
    global $base_url;

    $form['description_formulaire_contact'] = array(
      '#type'          => 'textarea',
      '#description'   => 'Entrer un texte que vous voulez afficher en entête dans le formulaire de contact',
      '#title'         => 'Descrition du formulaire de contact',
      '#default_value' => variable_get('description_contact', ''),
      '#required'      => FALSE,
      '#weight'        => -5
    );

    $form['#submit'][]         = "save_description";
    $form['actions']['submit'] = array(
      '#type'   => 'submit',
      '#value'  => t('Enregistrer'),
      '#weight' => 15,
      '#submit' => array('save_description_submit'),
    );


    $form['#action'] = $base_url . "/admin/structure/contact";
    return $form;
  }

  function save_description_submit(&$form, &$form_state) {
    variable_set('description_contact', $form_state['values']['description_formulaire_contact']);
    drupal_set_message("La description du formulaire de contact a été enregistrée");
  }


  function validate_email(&$form, &$form_state) {
    $email = $form_state['values']['mail'];
    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
      form_set_error('mail', "Cet adresse email n'est pas valide");
    }
  }

  /**
   * Implements hook_mail().
   */
  function osteo_contact_mail($key, &$message, $params) {
    $language = $message['language'];
    $variables = array(
      '!site-name' => variable_get('site_name', 'Drupal'),
      '!subject' => $params['subject'],
      '!category' => isset($params['category']['category']) ? $params['category']['category'] : '',
      '!form-url' => url($_GET['q'], array('absolute' => TRUE, 'language' => $language)),
      '!sender-name' => format_username($params['sender']),
      '!sender-url' => $params['sender']->uid ? url('user/' . $params['sender']->uid, array('absolute' => TRUE, 'language' => $language)) : $params['sender']->mail,
    );

    switch ($key) {
      case 'page_mail':
      case 'page_copy':
        $message['subject'] .= t('[!category] !subject', $variables, array('langcode' => $language->language));
        $message['body'][] = t("!sender-name (!sender-url) sent a message using the contact form at !form-url.", $variables, array('langcode' => $language->language));
        $message['body'][] = $params['message'];
        break;

      case 'page_autoreply':
        $message['subject'] .= t('[!category] !subject', $variables, array('langcode' => $language->language));
        $message['body'][] = $params['category']['reply'];
        break;

      case 'user_mail':
      case 'user_copy':
        $variables += array(
          '!recipient-name' => format_username($params['recipient']),
          '!recipient-edit-url' => url('user/' . $params['recipient']->uid . '/edit', array('absolute' => TRUE, 'language' => $language)),
        );
        $message['subject'] .= t('[!site-name] !subject', $variables, array('langcode' => $language->language));
        $message['body'][] = t('Hello !recipient-name,', $variables, array('langcode' => $language->language));
        $message['body'][] = t("!sender-name (!sender-url) has sent you a message via your contact form (!form-url) at !site-name.", $variables, array('langcode' => $language->language));
        $message['body'][] = t("If you don't want to receive such e-mails, you can change your settings at !recipient-edit-url.", $variables, array('langcode' => $language->language));
        $message['body'][] = t('Message:', array(), array('langcode' => $language->language));
        $message['body'][] = $params['message'];
        break;
    }
  }
  function osteo_contact_mail_alter(&$message) {
   // dsm($message , 'mess');
    $message['body'][] = $message['params']['name']  .' '. $message['params']['prenom'].' a choisi le cabinet de .'. $message['params']['cabinet'];
  }