<?php
  /**
   * first update
   */
  function osteo_update_update_7001(&$sandbox) {
    //desactivation des modules par defaut
    module_disable(array(
        'overlay',
        'toolbar'
      )
    );
    //activation des modules par default
    module_enable(array(
        'schema',
        'devel',
        'ds',
        'page_title',
        'pathauto',
        'uuid',
        'views',
        'admin_menu',
        'ckeditor',
        'imce',
        'imce_filefield',
        'jquery_plugin',
        'jquery_update',
        'libraries',
        'link',
        'pathauto',
        'pathologic',
        'transliteration',
        'token',
        'uuid',
        'xmlsitemap'
      ));
    // Caches
    cache_clear_all();
    return t('Mise à jour OK.');
    // In case of an error, simply throw an exception with an error message.
    throw new DrupalUpdateException('Erreur survenue.');
  }